#!/usr/bin/env python3
"""Generate deterministic Aurora Relay references from Python docstrings and extension manifests."""

from __future__ import annotations

import argparse
import ast
import json
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable


REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_SOURCE_ROOT = REPOSITORY_ROOT / "backend" / "app"
DEFAULT_MANIFEST_ROOT = REPOSITORY_ROOT / "backend" / "extensions" / "manifests"
DEFAULT_OUTPUT_ROOT = REPOSITORY_ROOT / "docs" / "generated"


@dataclass(frozen=True)
class DocumentedSymbol:
    """A public source symbol and its stable documentation summary."""

    qualified_name: str
    kind: str
    summary: str


def summary(docstring: str | None) -> str:
    """Normalize a source docstring into a single deterministic summary line."""

    if not docstring:
        return "No source docstring is currently provided."
    return " ".join(docstring.strip().split())


def is_public(name: str) -> bool:
    """Return whether a source symbol is part of the documentation surface."""

    return not name.startswith("_")


def documented_symbols(module_path: Path, source_root: Path) -> tuple[str, str, list[DocumentedSymbol]]:
    """Extract module and public class/function documentation through the Python AST."""

    relative = module_path.relative_to(source_root).with_suffix("")
    module_name = ".".join(relative.parts)
    tree = ast.parse(module_path.read_text(encoding="utf-8"), filename=str(module_path))
    symbols: list[DocumentedSymbol] = []

    for node in tree.body:
        if isinstance(node, ast.ClassDef) and is_public(node.name):
            symbols.append(DocumentedSymbol(f"{module_name}.{node.name}", "class", summary(ast.get_docstring(node))))
            for method in node.body:
                if isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)) and is_public(method.name):
                    symbols.append(
                        DocumentedSymbol(
                            f"{module_name}.{node.name}.{method.name}",
                            "method",
                            summary(ast.get_docstring(method)),
                        )
                    )
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and is_public(node.name):
            symbols.append(DocumentedSymbol(f"{module_name}.{node.name}", "function", summary(ast.get_docstring(node))))

    return module_name, summary(ast.get_docstring(tree)), symbols


def markdown_table(headers: Iterable[str], rows: Iterable[Iterable[str]]) -> list[str]:
    """Render a small, escape-safe Markdown table."""

    safe_headers = [header.replace("|", "\\|") for header in headers]
    lines = ["| " + " | ".join(safe_headers) + " |", "| " + " | ".join("---" for _ in safe_headers) + " |"]
    for row in rows:
        lines.append("| " + " | ".join(str(cell).replace("|", "\\|") for cell in row) + " |")
    return lines


def build_backend_reference(source_root: Path) -> str:
    """Build a stable reference for documented backend source symbols."""

    lines = [
        "# Generated backend reference",
        "",
        "> This file is generated by `python scripts/generate_docs.py`. Edit source docstrings, not this file.",
        "",
    ]
    for module_path in sorted(source_root.rglob("*.py")):
        if "__pycache__" in module_path.parts:
            continue
        module_name, module_summary, symbols = documented_symbols(module_path, source_root)
        if not symbols and module_summary == "No source docstring is currently provided.":
            continue
        lines.extend([f"## `{module_name}`", "", module_summary, ""])
        if symbols:
            lines.extend(markdown_table(["Symbol", "Kind", "Source summary"], ((f"`{symbol.qualified_name}`", symbol.kind, symbol.summary) for symbol in symbols)))
            lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def build_extension_reference(manifest_root: Path) -> str:
    """Build a stable reference for reviewed local extension manifests."""

    manifests: list[dict[str, object]] = []
    for manifest_path in sorted(manifest_root.glob("*.json")):
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
        manifests.append(manifest)

    lines = [
        "# Generated extension reference",
        "",
        "> This file is generated from checked-in local manifests by `python scripts/generate_docs.py`. It never reads remote package catalogs.",
        "",
    ]
    if not manifests:
        return "\n".join(lines + ["No reviewed extension manifests are present."]) + "\n"

    rows = []
    for manifest in manifests:
        permissions = ", ".join(str(value) for value in manifest.get("permissions", [])) or "None"
        connector = str(manifest.get("connector_provider") or "—")
        rows.append(
            (
                f"`{manifest['id']}`",
                str(manifest.get("display_name", manifest["id"])),
                str(manifest.get("version", "—")),
                str(manifest.get("kind", "—")),
                permissions,
                connector,
                str(manifest.get("description", "No description provided.")),
            )
        )
    lines.extend(markdown_table(["Identifier", "Name", "Version", "Kind", "Declared permissions", "Connector", "Purpose"], rows))
    lines.extend(
        [
            "",
            "## Execution boundary",
            "",
            "Reviewed manifests do not grant host-process access. Sandboxed tool execution remains Docker-only and fails closed when the sandbox is unavailable.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def generated_documents(source_root: Path, manifest_root: Path) -> dict[Path, str]:
    """Return every generated documentation path and deterministic content."""

    return {
        Path("backend-reference.md"): build_backend_reference(source_root),
        Path("extensions-reference.md"): build_extension_reference(manifest_root),
    }


def apply_documents(documents: dict[Path, str], output_root: Path, check: bool) -> int:
    """Write generated documents or verify that checked-in outputs are current."""

    stale: list[Path] = []
    for relative_path, content in documents.items():
        destination = output_root / relative_path
        if check:
            if not destination.exists() or destination.read_text(encoding="utf-8") != content:
                stale.append(destination)
            continue
        destination.parent.mkdir(parents=True, exist_ok=True)
        destination.write_text(content, encoding="utf-8")

    if stale:
        print("Generated documentation is stale:")
        for destination in stale:
            print(f"- {destination}")
        print("Run: python scripts/generate_docs.py")
        return 1
    return 0


def main() -> int:
    """Generate or verify references from local reviewed source only."""

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail when committed generated documentation differs from local source.")
    parser.add_argument("--source-root", type=Path, default=DEFAULT_SOURCE_ROOT)
    parser.add_argument("--manifest-root", type=Path, default=DEFAULT_MANIFEST_ROOT)
    parser.add_argument("--output-root", type=Path, default=DEFAULT_OUTPUT_ROOT)
    args = parser.parse_args()
    return apply_documents(generated_documents(args.source_root, args.manifest_root), args.output_root, args.check)


if __name__ == "__main__":
    raise SystemExit(main())
